# Site settings
title: पुरानो रेडियो
email: nischal.mainali@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  Curated Articles from Nepali media spanning Society, Politics, and Literature
url:  # the subpath of your site, e.g. /blog/
baseurl:
twitter_username: psharma3123
github_username:  5183nischal

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


